name: lingobattle
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  http: ^0.13.6
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.3
  stroke_text: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/german.png
    - assets/netherlands.png
    - assets/schweiz.png
    - assets/button_green.png
    - assets/button_grey.png
    - assets/button_mint.png
    - assets/button_locked.png
