name: lingobattle
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.0.3
  stroke_text: ^0.0.2
  socket_io_client: ^2.0.3+1
  flutter_neumorphic: ^3.2.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.2
  lottie: ^3.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/flags/german.png
    - assets/flags/dutch.png
    - assets/flags/swiss.png
    - assets/flags/english.png
    - assets/flags/spanish.png
    - assets/logo.png
    - assets/button_green.png
    - assets/button_grey.png
    - assets/button_mint.png
    - assets/button_locked.png
    - assets/crown.png
    - assets/flame.png
    - assets/correct.mp3
    - assets/wrong.mp3
    - assets/correct.json
    - assets/wrong.json

