name: lingobattle
description: "A new Flutter project."

version: 1.0.0+5

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.1.3
  stroke_text: ^0.0.2
  socket_io_client: ^2.0.3+1
  flutter_neumorphic: ^3.2.0
  google_fonts: ^6.2.1
  audioplayers: ^6.1.2
  lottie: ^3.2.0

dev_dependencies:

  flutter_launcher_icons: ^0.14.3

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/playstorelogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/playstorelogo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/playstorelogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/playstorelogo.png"

  flutter_lints: ^4.0.0    

flutter:

  uses-material-design: true

  assets:
    - assets/flags/german.png
    - assets/flags/dutch.png
    - assets/flags/swiss.png
    - assets/flags/english.png
    - assets/flags/spanish.png
    - assets/flags_20x20/german.png
    - assets/flags_20x20/dutch.png
    - assets/flags_20x20/swiss.png
    - assets/flags_20x20/english.png
    - assets/flags_20x20/spanish.png
    - assets/logo.png
    - assets/playstorelogo.png
    - assets/button_green.png
    - assets/button_grey.png
    - assets/button_mint.png
    - assets/button_locked.png
    - assets/crown.png
    - assets/flame.png
    - assets/correct.mp3
    - assets/wrong.mp3
    - assets/correct.json
    - assets/wrong.json
    - assets/ranks/baby01.png
    - assets/ranks/baby02.png
    - assets/ranks/baby03.png
    - assets/ranks/baby04.png
    - assets/ranks/beginner01.png
    - assets/ranks/beginner02.png
    - assets/ranks/beginner03.png
    - assets/ranks/beginner04.png
    - assets/ranks/novice01.png
    - assets/ranks/novice02.png
    - assets/ranks/novice03.png
    - assets/ranks/novice04.png
    - assets/ranks/expert01.png
    - assets/ranks/expert02.png
    - assets/ranks/expert03.png
    - assets/ranks/expert04.png

